replicaCount: 2

image:
  repository: abdallaabdelsalam/app
  tag: latest
  containerPort: 9090


service:
  type: NodePort
  port: 9090
  targetPort: 9090
  nodePort: 30000

persistence:
  enabled: true
  size: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

mysql:
  rootPassword: password
  username: root
  password: password
