apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: {{ .Release.Name }}
    component: mysql
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: standard
  volumeName: mysql-pv
  resources:
    requests:
      storage: {{ .Values.persistence.size }}