apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
  labels:
    app: {{ .Release.Name }}
    component: mysql
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  username: {{ .Values.mysql.username | b64enc | quote }}
  password: {{ .Values.mysql.password | b64enc | quote }}
