apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Release.Name }}
    component: mysql
spec:
  selector:
    app: {{ .Release.Name }}
    component: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
